### ISSUE TITLE
SideBar Issue

### ISSUE THREAD

**Issue by Antagonist427** [gamerfunky78/Fresco-wallpapers#2]
I visited your website a few months ago and got the problem of the sidebar not collapsing after i clicked on the navigating buttons at the moment i just wanted to know if you had updated this issue.

**Comment by Brianali-codes** [comment]
I had noticed the issue a while back and fixed it but thanks for the acknowledging about it, I strive to make better websites due to people like you who come forward and express their says on my products

**Comment by Antagonist427** [comment]
yeah i noticed, thanks for the update.
